import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

export default function Home({ pokemons }) {
  console.log(pokemons);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {pokemons.map((pokemon, key) => {
          return <div key={key}>{pokemon.name}</div>;
        })}
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { data } = await axios.get(
    "https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json"
  );

  const pokemons = data;

  return {
    props: {
      pokemons,
    },
  };
}
